---
title: "Lecture Notes"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
    theme: flatly
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F, message = F)
```

******

<br>

## Lecture 1: Introduction

* [Slides](https://drive.google.com/file/d/13qSkBDwcFy_tD8F3uUtHoB6Uzgi16vfA/view?usp=sharing)

* [Slides with scribbles - 101](https://drive.google.com/file/d/1iEsFxujp_gUBjFfQHIMHgG6KnvxovQ0V/view?usp=sharing)

* [Slides with scribbles - 201]()

* [Probability Review](https://drive.google.com/file/d/1hv-cv7T0ZCyTsPxX0BOWXg1S0KOxI2Yr/view?usp=sharing)

## Lecture 2: Limit Theorems

* [Slides]()

* [Slides with scribbles - 101]()

* [Slides with scribbles - 201]()

## Lecture 3: Normal Theory \& Sampling

* [Slides]()

* [Slides with scribbles - 101]()

* [Slides with scribbles - 201]()

## Lecture 4: Estimation Methods

* [Slides]()

* [Slides with scribbles - 101]()

* [Slides with scribbles - 201]()

## Lecture 5: MLE Asymptotics

* [Slides]()

* [Slides with scribbles - 101]()

* [Slides with scribbles - 201]()

## Lecture 6: Optimality

* [Slides]()

* [Slides with scribbles - 101]()

* [Slides with scribbles - 201]()

## Lecture 7: Hypothesis Testing \& Bayesian Inference

* [Slides]()

* [Slides with scribbles - 101]()

* [Slides with scribbles - 201]()

## Lecture 8: Linear Regression

* [Slides]()

* [Slides with scribbles - 101]()

* [Slides with scribbles - 201]()

## Lecture 9: Review

* [Slides]()

* [Slides with scribbles - 101]()

* [Slides with scribbles - 201]()
