---
title: ""
output: 
  html_document:
   toc: true
   toc_float: true
   theme: flatly
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
knitr::opts_chunk$set(warning = F, message = F)
```
<br>

# <span class="glyphicon glyphicon-calendar" aria-hidden="false"></span> Course Schedule
Below is our course schedule, which will almost certainly change as the course progresses.  

| **Weeks**                        | **Topics**                                               | **Reading**  |
|----------------------------------|-----------------------------------------------------------|--------------|
| Week 1 (Jan. 05 – Jan. 09)       | Lecture 1: Course Introduction, Review                    | Chps 1–3     |
| Week 2 (Jan. 12 – Jan. 16)       | Lecture 2: Limit Theorems, Review                         | Chp 4–5      |
| Week 3 (Jan. 19 – Jan. 23)       | Lecture 3: Normal Theory                                  | Chp 6      |
| Week 4 (Jan. 26 – Jan. 30)       | Snow Day                                                 |              |
| Week 5 (Feb. 02 – Feb. 06)       | Test 1                                              |        |
| Week 6 (Feb. 09 – Feb. 13)       | Lecture 4: Sampling, Method of Moments                       | Chp 7-8       |
| **Reading Week (Feb. 16 – Feb. 20)** |                                                      |            |
| Week 7 (Feb. 23 – Feb. 27)       | Lecture 5: Maximum Likelihood Estimation                             | Chp 8        |
| Week 8 (Mar. 02 – Mar. 06)       | Test 2                                                    |              |
| Week 9 (Mar. 09 – Mar. 13)       | Lecture 6: MLE Asymptotics                                    | Chp 8      |
| Week 10 (Mar. 16 – Mar. 20)      | Lecture 7:  Hypothesis Testing         | Chp 8–9       |
| Week 11 (Mar. 23 – Mar. 27)      | Lecture 8: Bayesian Inference                             |   Chp 14     |
| Week 12 (Mar. 30 – Apr. 03)      | Lecture 9:  Linear Regression, Review                                             |   Chp 14           |

<br>

# <span class="glyphicon glyphicon-time" aria-hidden="false"></span> Weekly Office Hour Schedule

| **TA**  | **Time**  | **Zoom** |
|----------|-----------|----------|
| Jianhui  | Wednesday 14:30–15:30 | <a href="https://utoronto.zoom.us/j/84584056034" target="_blank" rel="noopener">Zoom link</a> |
| KC       | Thursdays 10:00–11:00 | <a href="https://utoronto.zoom.us/j/87209490546" target="_blank" rel="noopener">Zoom link</a> |
| Yuan     | Thursday 14:00–15:00 | <a href="https://utoronto.zoom.us/j/9569880493" target="_blank" rel="noopener">Zoom link</a> |
| Weicheng | Friday 15:00–16:00 | <a href="https://utoronto.zoom.us/j/83358989754" target="_blank" rel="noopener">Zoom link</a> |
| David    | Friday 14:00–15:00 | <a href="https://utoronto.zoom.us/j/89223782802" target="_blank" rel="noopener">Zoom link</a> |

<br>

# <span class="glyphicon glyphicon-plus" aria-hidden="false"></span> Extra Office Hour

| **Name** | **Time** | **Zoom** |
|---------|----------|----------|
| Alex  | January 23, February 27 (Fridays) 16:00–17:00 | <a href="https://utoronto.zoom.us/j/86515559105" target="_blank" rel="noopener">Zoom link</a> |
| Madhu | January 23, February 27 (Fridays) 13:00–14:00 | <a href="https://utoronto.zoom.us/j/4133047143" target="_blank" rel="noopener">Zoom link</a> |
| Prof | January 27 14:10-15:00 | <a href="https://utoronto.zoom.us/j/81083876621" target="_blank" rel="noopener">Zoom link</a> |
| Prof | February 24 14:40-15:30 | <a href="https://utoronto.zoom.us/j/82066753873" target="_blank" rel="noopener">Zoom link</a> |

# <span class="glyphicon glyphicon-plus" aria-hidden="false"></span> Final Exam Office Hour

| **Name** | **Time** | **Zoom** |
|---------|----------|----------|
| KC  | April 9, 10:00–11:00 | <a href="https://utoronto.zoom.us/j/87209490546" target="_blank" rel="noopener">Zoom link</a> |
| David  | April 9, 14:00–15:00 | <a href="https://utoronto.zoom.us/j/6095211024?omn=88938307937" target="_blank" rel="noopener">Zoom link</a> |
| Madhu  | April 10, 12:00–14:00 | <a href="https://utoronto.zoom.us/j/87289661946" target="_blank" rel="noopener">Zoom link</a> |
| Madhu  | April 13, 12:00–14:00 | <a href="https://utoronto.zoom.us/j/87289661946" target="_blank" rel="noopener">Zoom link</a> |
| KC  | April 16, 10:00–11:00 | <a href="https://utoronto.zoom.us/j/87209490546" target="_blank" rel="noopener">Zoom link</a> |
| Prof | April 16 14:00-15:00 | <a href="https://utoronto.zoom.us/j/81889559804" target="_blank" rel="noopener">Zoom link</a> |
| David  | April 16, 13:00–14:00 | <a href="https://utoronto.zoom.us/j/6095211024?omn=88938307937" target="_blank" rel="noopener">Zoom link</a> |
| David  | April 17, 14:00–15:00 | <a href="https://utoronto.zoom.us/j/6095211024?omn=88938307937" target="_blank" rel="noopener">Zoom link</a> |
| David  | April 20, 14:00–15:00 | <a href="https://utoronto.zoom.us/j/6095211024?omn=88938307937" target="_blank" rel="noopener">Zoom link</a> |
| Weicheng  | April 21, 15:00–16:00 | <a href="https://utoronto.zoom.us/j/83358989754" target="_blank" rel="noopener">Zoom link</a> |
| Alex  | April 22, 13:00–14:00 | <a href="https://utoronto.zoom.us/j/86515559105" target="_blank" rel="noopener">Zoom link</a> |
| KC  | April 23, 10:00–11:00 | <a href="https://utoronto.zoom.us/j/87209490546" target="_blank" rel="noopener">Zoom link</a> |

